"""

# RelianceConstant.py

## Constants
* BOOLEAN_FALSE: Integer
* BOOLEAN_TRUE: Integer
* DATASOURCE_MAPPING: String
* DATASOURCE_NAME: String
* DEBUG: Boolean
* FIELD_SYSTEM_CREATEDDATE: String
* FIELD_SYSTEM_CURRENTPHASE: String
* FIELD_SYSTEM_CURRENTWORKFLOW: String
* FIELD_SYSTEM_DUEDATE: String
* FIELD_SYSTEM_EDITORS: String
* FIELD_SYSTEM_MANAGERS: String
* FIELD_SYSTEM_NUMBER: String
* FIELD_SYSTEM_READERS: String
* KEYWORD_SEPARATOR: String

"""

BOOLEAN_FALSE=0
BOOLEAN_TRUE=1
DATASOURCE_MAPPING="ETQ$SELECT_STATEMENT"
DATASOURCE_NAME="DAO_SELECT_STATEMENT"
DEBUG=false
FIELD_SYSTEM_CREATEDDATE="ETQ$CREATED_DATE"
FIELD_SYSTEM_CURRENTPHASE="ETQ$CURRENT_PHASE"
FIELD_SYSTEM_CURRENTWORKFLOW="ETQ$CURRENT_WORKFLOW"
FIELD_SYSTEM_DUEDATE="ETQ$DUE_DATE"
FIELD_SYSTEM_EDITORS="ETQ$EDITORS"
FIELD_SYSTEM_MANAGERS="ETQ$MANAGERS"
FIELD_SYSTEM_NUMBER="ETQ$NUMBER"
FIELD_SYSTEM_READERS="ETQ$READERS"
KEYWORD_SEPARATOR=" : "
